<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MotsCandidat', 'doctrine');

/**
 * BaseMotsCandidat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $mot
 * @property integer $candidat_id
 * @property integer $poids
 * @property Candidat $Candidat
 * @property Mots $Mots
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method string       getMot()         Returns the current record's "mot" value
 * @method integer      getCandidatId()  Returns the current record's "candidat_id" value
 * @method integer      getPoids()       Returns the current record's "poids" value
 * @method Candidat     getCandidat()    Returns the current record's "Candidat" value
 * @method Mots         getMots()        Returns the current record's "Mots" value
 * @method MotsCandidat setId()          Sets the current record's "id" value
 * @method MotsCandidat setMot()         Sets the current record's "mot" value
 * @method MotsCandidat setCandidatId()  Sets the current record's "candidat_id" value
 * @method MotsCandidat setPoids()       Sets the current record's "poids" value
 * @method MotsCandidat setCandidat()    Sets the current record's "Candidat" value
 * @method MotsCandidat setMots()        Sets the current record's "Mots" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMotsCandidat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mots_candidat');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mot', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('candidat_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('poids', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Candidat', array(
             'local' => 'candidat_id',
             'foreign' => 'id'));

        $this->hasOne('Mots', array(
             'local' => 'mot',
             'foreign' => 'mot'));
    }
}