<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Groupe', 'doctrine');

/**
 * BaseGroupe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * @property Doctrine_Collection $UserGroup
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getLibelle()   Returns the current record's "libelle" value
 * @method Doctrine_Collection getUserGroup() Returns the current record's "UserGroup" collection
 * @method Groupe              setId()        Sets the current record's "id" value
 * @method Groupe              setLibelle()   Sets the current record's "libelle" value
 * @method Groupe              setUserGroup() Sets the current record's "UserGroup" collection
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('groupe');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserGroup', array(
             'local' => 'id',
             'foreign' => 'groupe_id'));
    }
}