<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CtrlStatutMission', 'doctrine');

/**
 * BaseCtrlStatutMission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * @property integer $ordre
 * 
 * @method integer           getId()      Returns the current record's "id" value
 * @method string            getLibelle() Returns the current record's "libelle" value
 * @method integer           getOrdre()   Returns the current record's "ordre" value
 * @method CtrlStatutMission setId()      Sets the current record's "id" value
 * @method CtrlStatutMission setLibelle() Sets the current record's "libelle" value
 * @method CtrlStatutMission setOrdre()   Sets the current record's "ordre" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCtrlStatutMission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ctrl_statut_mission');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('ordre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}