<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Couleurs', 'doctrine');

/**
 * BaseCouleurs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $valeur
 * 
 * @method string   getId()     Returns the current record's "id" value
 * @method string   getValeur() Returns the current record's "valeur" value
 * @method Couleurs setId()     Sets the current record's "id" value
 * @method Couleurs setValeur() Sets the current record's "valeur" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCouleurs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('couleurs');
        $this->hasColumn('id', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('valeur', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}