<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MotsParcour', 'doctrine');

/**
 * BaseMotsParcour
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $mot
 * @property integer $parcour_id
 * @property integer $poids
 * @property Parcour $Parcour
 * @property Mots $Mots
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method string      getMot()        Returns the current record's "mot" value
 * @method integer     getParcourId()  Returns the current record's "parcour_id" value
 * @method integer     getPoids()      Returns the current record's "poids" value
 * @method Parcour     getParcour()    Returns the current record's "Parcour" value
 * @method Mots        getMots()       Returns the current record's "Mots" value
 * @method MotsParcour setId()         Sets the current record's "id" value
 * @method MotsParcour setMot()        Sets the current record's "mot" value
 * @method MotsParcour setParcourId()  Sets the current record's "parcour_id" value
 * @method MotsParcour setPoids()      Sets the current record's "poids" value
 * @method MotsParcour setParcour()    Sets the current record's "Parcour" value
 * @method MotsParcour setMots()       Sets the current record's "Mots" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMotsParcour extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mots_parcour');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mot', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('parcour_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('poids', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parcour', array(
             'local' => 'parcour_id',
             'foreign' => 'id'));

        $this->hasOne('Mots', array(
             'local' => 'mot',
             'foreign' => 'mot'));
    }
}