<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CtrlStatut', 'doctrine');

/**
 * BaseCtrlStatut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * 
 * @method integer    getId()      Returns the current record's "id" value
 * @method string     getLibelle() Returns the current record's "libelle" value
 * @method CtrlStatut setId()      Sets the current record's "id" value
 * @method CtrlStatut setLibelle() Sets the current record's "libelle" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCtrlStatut extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ctrl_statut');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}