<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PlaquetteSecteur', 'doctrine');

/**
 * BasePlaquetteSecteur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $secteur
 * @property integer $nb_candidat
 * @property integer $nb_societe
 * @property integer $nb_mission
 * @property clob $poste
 * @property clob $client
 * @property integer $mediane_salariale
 * @property clob $loc_pourcent
 * @property integer $taux_reussite
 * @property boolean $aff_secteur
 * @property boolean $aff_nb_candidat
 * @property boolean $aff_nb_societe
 * @property boolean $aff_nb_mission
 * @property boolean $aff_poste
 * @property boolean $aff_client
 * @property boolean $aff_mediane_salariale
 * @property boolean $aff_loc_pourcent
 * @property boolean $aff_taux_reussite
 * @property integer $utilisateur_id
 * @property boolean $saved
 * 
 * @method clob             getSecteur()               Returns the current record's "secteur" value
 * @method integer          getNbCandidat()            Returns the current record's "nb_candidat" value
 * @method integer          getNbSociete()             Returns the current record's "nb_societe" value
 * @method integer          getNbMission()             Returns the current record's "nb_mission" value
 * @method clob             getPoste()                 Returns the current record's "poste" value
 * @method clob             getClient()                Returns the current record's "client" value
 * @method integer          getMedianeSalariale()      Returns the current record's "mediane_salariale" value
 * @method clob             getLocPourcent()           Returns the current record's "loc_pourcent" value
 * @method integer          getTauxReussite()          Returns the current record's "taux_reussite" value
 * @method boolean          getAffSecteur()            Returns the current record's "aff_secteur" value
 * @method boolean          getAffNbCandidat()         Returns the current record's "aff_nb_candidat" value
 * @method boolean          getAffNbSociete()          Returns the current record's "aff_nb_societe" value
 * @method boolean          getAffNbMission()          Returns the current record's "aff_nb_mission" value
 * @method boolean          getAffPoste()              Returns the current record's "aff_poste" value
 * @method boolean          getAffClient()             Returns the current record's "aff_client" value
 * @method boolean          getAffMedianeSalariale()   Returns the current record's "aff_mediane_salariale" value
 * @method boolean          getAffLocPourcent()        Returns the current record's "aff_loc_pourcent" value
 * @method boolean          getAffTauxReussite()       Returns the current record's "aff_taux_reussite" value
 * @method integer          getUtilisateurId()         Returns the current record's "utilisateur_id" value
 * @method boolean          getSaved()                 Returns the current record's "saved" value
 * @method PlaquetteSecteur setSecteur()               Sets the current record's "secteur" value
 * @method PlaquetteSecteur setNbCandidat()            Sets the current record's "nb_candidat" value
 * @method PlaquetteSecteur setNbSociete()             Sets the current record's "nb_societe" value
 * @method PlaquetteSecteur setNbMission()             Sets the current record's "nb_mission" value
 * @method PlaquetteSecteur setPoste()                 Sets the current record's "poste" value
 * @method PlaquetteSecteur setClient()                Sets the current record's "client" value
 * @method PlaquetteSecteur setMedianeSalariale()      Sets the current record's "mediane_salariale" value
 * @method PlaquetteSecteur setLocPourcent()           Sets the current record's "loc_pourcent" value
 * @method PlaquetteSecteur setTauxReussite()          Sets the current record's "taux_reussite" value
 * @method PlaquetteSecteur setAffSecteur()            Sets the current record's "aff_secteur" value
 * @method PlaquetteSecteur setAffNbCandidat()         Sets the current record's "aff_nb_candidat" value
 * @method PlaquetteSecteur setAffNbSociete()          Sets the current record's "aff_nb_societe" value
 * @method PlaquetteSecteur setAffNbMission()          Sets the current record's "aff_nb_mission" value
 * @method PlaquetteSecteur setAffPoste()              Sets the current record's "aff_poste" value
 * @method PlaquetteSecteur setAffClient()             Sets the current record's "aff_client" value
 * @method PlaquetteSecteur setAffMedianeSalariale()   Sets the current record's "aff_mediane_salariale" value
 * @method PlaquetteSecteur setAffLocPourcent()        Sets the current record's "aff_loc_pourcent" value
 * @method PlaquetteSecteur setAffTauxReussite()       Sets the current record's "aff_taux_reussite" value
 * @method PlaquetteSecteur setUtilisateurId()         Sets the current record's "utilisateur_id" value
 * @method PlaquetteSecteur setSaved()                 Sets the current record's "saved" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlaquetteSecteur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plaquette_secteur');
        $this->hasColumn('secteur', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('nb_candidat', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nb_societe', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nb_mission', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('poste', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('client', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('mediane_salariale', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('loc_pourcent', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('taux_reussite', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('aff_secteur', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_nb_candidat', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_nb_societe', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_nb_mission', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_poste', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_client', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_mediane_salariale', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_loc_pourcent', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_taux_reussite', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('utilisateur_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('saved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}