<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CtrlSecteur', 'doctrine');

/**
 * BaseCtrlSecteur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $secteur
 * 
 * @method string      getSecteur() Returns the current record's "secteur" value
 * @method CtrlSecteur setSecteur() Sets the current record's "secteur" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCtrlSecteur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ctrl_secteur');
        $this->hasColumn('secteur', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}