<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CtrlFonction', 'doctrine');

/**
 * BaseCtrlFonction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $fonction
 * 
 * @method string       getFonction() Returns the current record's "fonction" value
 * @method CtrlFonction setFonction() Sets the current record's "fonction" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCtrlFonction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ctrl_fonction');
        $this->hasColumn('fonction', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}