<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CtrlNiveauFormation', 'doctrine');

/**
 * BaseCtrlNiveauFormation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $niveauformation
 * 
 * @method string              getNiveauformation() Returns the current record's "niveauformation" value
 * @method CtrlNiveauFormation setNiveauformation() Sets the current record's "niveauformation" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCtrlNiveauFormation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ctrl_niveau_formation');
        $this->hasColumn('niveauformation', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}