<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MotsFormation', 'doctrine');

/**
 * BaseMotsFormation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $mot
 * @property integer $formation_id
 * @property integer $poids
 * @property Formation $Formation
 * @property Mots $Mots
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method string        getMot()          Returns the current record's "mot" value
 * @method integer       getFormationId()  Returns the current record's "formation_id" value
 * @method integer       getPoids()        Returns the current record's "poids" value
 * @method Formation     getFormation()    Returns the current record's "Formation" value
 * @method Mots          getMots()         Returns the current record's "Mots" value
 * @method MotsFormation setId()           Sets the current record's "id" value
 * @method MotsFormation setMot()          Sets the current record's "mot" value
 * @method MotsFormation setFormationId()  Sets the current record's "formation_id" value
 * @method MotsFormation setPoids()        Sets the current record's "poids" value
 * @method MotsFormation setFormation()    Sets the current record's "Formation" value
 * @method MotsFormation setMots()         Sets the current record's "Mots" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMotsFormation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mots_formation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mot', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('formation_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('poids', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Formation', array(
             'local' => 'formation_id',
             'foreign' => 'id'));

        $this->hasOne('Mots', array(
             'local' => 'mot',
             'foreign' => 'mot'));
    }
}