<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PlaquetteMetier', 'doctrine');

/**
 * BasePlaquetteMetier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $intitule_post
 * @property integer $nb_candidat
 * @property integer $rem_moy
 * @property integer $rem_max
 * @property integer $id_cand_max
 * @property integer $rem_min
 * @property integer $id_cand_min
 * @property integer $secteur_pourcent
 * @property clob $formation_pourcent
 * @property clob $loc_pourcent
 * @property integer $age_moy
 * @property integer $age_min
 * @property integer $age_max
 * @property integer $taux_reussite
 * @property clob $commentaire
 * @property boolean $aff_intitule_post
 * @property boolean $aff_nb_candidat
 * @property boolean $aff_rem_moy
 * @property boolean $aff_rem_max
 * @property boolean $aff_age_cand_max
 * @property boolean $aff_formation_cand_max
 * @property boolean $aff_societe_prov_cand_max
 * @property boolean $aff_rem_min
 * @property boolean $aff_age_cand_min
 * @property boolean $aff_formation_cand_min
 * @property boolean $aff_societe_prov_cand_min
 * @property boolean $aff_secteur_pourcent
 * @property boolean $aff_formation_pourcent
 * @property boolean $aff_loc_pourcent
 * @property boolean $aff_age_moy
 * @property boolean $aff_age_min
 * @property boolean $aff_age_max
 * @property boolean $aff_commentaire
 * @property integer $utilisateur_id
 * @property boolean $saved
 * @property Utilisateur $Utilisateur
 * 
 * @method clob            getIntitulePost()              Returns the current record's "intitule_post" value
 * @method integer         getNbCandidat()                Returns the current record's "nb_candidat" value
 * @method integer         getRemMoy()                    Returns the current record's "rem_moy" value
 * @method integer         getRemMax()                    Returns the current record's "rem_max" value
 * @method integer         getIdCandMax()                 Returns the current record's "id_cand_max" value
 * @method integer         getRemMin()                    Returns the current record's "rem_min" value
 * @method integer         getIdCandMin()                 Returns the current record's "id_cand_min" value
 * @method integer         getSecteurPourcent()           Returns the current record's "secteur_pourcent" value
 * @method clob            getFormationPourcent()         Returns the current record's "formation_pourcent" value
 * @method clob            getLocPourcent()               Returns the current record's "loc_pourcent" value
 * @method integer         getAgeMoy()                    Returns the current record's "age_moy" value
 * @method integer         getAgeMin()                    Returns the current record's "age_min" value
 * @method integer         getAgeMax()                    Returns the current record's "age_max" value
 * @method integer         getTauxReussite()              Returns the current record's "taux_reussite" value
 * @method clob            getCommentaire()               Returns the current record's "commentaire" value
 * @method boolean         getAffIntitulePost()           Returns the current record's "aff_intitule_post" value
 * @method boolean         getAffNbCandidat()             Returns the current record's "aff_nb_candidat" value
 * @method boolean         getAffRemMoy()                 Returns the current record's "aff_rem_moy" value
 * @method boolean         getAffRemMax()                 Returns the current record's "aff_rem_max" value
 * @method boolean         getAffAgeCandMax()             Returns the current record's "aff_age_cand_max" value
 * @method boolean         getAffFormationCandMax()       Returns the current record's "aff_formation_cand_max" value
 * @method boolean         getAffSocieteProvCandMax()     Returns the current record's "aff_societe_prov_cand_max" value
 * @method boolean         getAffRemMin()                 Returns the current record's "aff_rem_min" value
 * @method boolean         getAffAgeCandMin()             Returns the current record's "aff_age_cand_min" value
 * @method boolean         getAffFormationCandMin()       Returns the current record's "aff_formation_cand_min" value
 * @method boolean         getAffSocieteProvCandMin()     Returns the current record's "aff_societe_prov_cand_min" value
 * @method boolean         getAffSecteurPourcent()        Returns the current record's "aff_secteur_pourcent" value
 * @method boolean         getAffFormationPourcent()      Returns the current record's "aff_formation_pourcent" value
 * @method boolean         getAffLocPourcent()            Returns the current record's "aff_loc_pourcent" value
 * @method boolean         getAffAgeMoy()                 Returns the current record's "aff_age_moy" value
 * @method boolean         getAffAgeMin()                 Returns the current record's "aff_age_min" value
 * @method boolean         getAffAgeMax()                 Returns the current record's "aff_age_max" value
 * @method boolean         getAffCommentaire()            Returns the current record's "aff_commentaire" value
 * @method integer         getUtilisateurId()             Returns the current record's "utilisateur_id" value
 * @method boolean         getSaved()                     Returns the current record's "saved" value
 * @method Utilisateur     getUtilisateur()               Returns the current record's "Utilisateur" value
 * @method PlaquetteMetier setIntitulePost()              Sets the current record's "intitule_post" value
 * @method PlaquetteMetier setNbCandidat()                Sets the current record's "nb_candidat" value
 * @method PlaquetteMetier setRemMoy()                    Sets the current record's "rem_moy" value
 * @method PlaquetteMetier setRemMax()                    Sets the current record's "rem_max" value
 * @method PlaquetteMetier setIdCandMax()                 Sets the current record's "id_cand_max" value
 * @method PlaquetteMetier setRemMin()                    Sets the current record's "rem_min" value
 * @method PlaquetteMetier setIdCandMin()                 Sets the current record's "id_cand_min" value
 * @method PlaquetteMetier setSecteurPourcent()           Sets the current record's "secteur_pourcent" value
 * @method PlaquetteMetier setFormationPourcent()         Sets the current record's "formation_pourcent" value
 * @method PlaquetteMetier setLocPourcent()               Sets the current record's "loc_pourcent" value
 * @method PlaquetteMetier setAgeMoy()                    Sets the current record's "age_moy" value
 * @method PlaquetteMetier setAgeMin()                    Sets the current record's "age_min" value
 * @method PlaquetteMetier setAgeMax()                    Sets the current record's "age_max" value
 * @method PlaquetteMetier setTauxReussite()              Sets the current record's "taux_reussite" value
 * @method PlaquetteMetier setCommentaire()               Sets the current record's "commentaire" value
 * @method PlaquetteMetier setAffIntitulePost()           Sets the current record's "aff_intitule_post" value
 * @method PlaquetteMetier setAffNbCandidat()             Sets the current record's "aff_nb_candidat" value
 * @method PlaquetteMetier setAffRemMoy()                 Sets the current record's "aff_rem_moy" value
 * @method PlaquetteMetier setAffRemMax()                 Sets the current record's "aff_rem_max" value
 * @method PlaquetteMetier setAffAgeCandMax()             Sets the current record's "aff_age_cand_max" value
 * @method PlaquetteMetier setAffFormationCandMax()       Sets the current record's "aff_formation_cand_max" value
 * @method PlaquetteMetier setAffSocieteProvCandMax()     Sets the current record's "aff_societe_prov_cand_max" value
 * @method PlaquetteMetier setAffRemMin()                 Sets the current record's "aff_rem_min" value
 * @method PlaquetteMetier setAffAgeCandMin()             Sets the current record's "aff_age_cand_min" value
 * @method PlaquetteMetier setAffFormationCandMin()       Sets the current record's "aff_formation_cand_min" value
 * @method PlaquetteMetier setAffSocieteProvCandMin()     Sets the current record's "aff_societe_prov_cand_min" value
 * @method PlaquetteMetier setAffSecteurPourcent()        Sets the current record's "aff_secteur_pourcent" value
 * @method PlaquetteMetier setAffFormationPourcent()      Sets the current record's "aff_formation_pourcent" value
 * @method PlaquetteMetier setAffLocPourcent()            Sets the current record's "aff_loc_pourcent" value
 * @method PlaquetteMetier setAffAgeMoy()                 Sets the current record's "aff_age_moy" value
 * @method PlaquetteMetier setAffAgeMin()                 Sets the current record's "aff_age_min" value
 * @method PlaquetteMetier setAffAgeMax()                 Sets the current record's "aff_age_max" value
 * @method PlaquetteMetier setAffCommentaire()            Sets the current record's "aff_commentaire" value
 * @method PlaquetteMetier setUtilisateurId()             Sets the current record's "utilisateur_id" value
 * @method PlaquetteMetier setSaved()                     Sets the current record's "saved" value
 * @method PlaquetteMetier setUtilisateur()               Sets the current record's "Utilisateur" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlaquetteMetier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plaquette_metier');
        $this->hasColumn('intitule_post', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('nb_candidat', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rem_moy', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rem_max', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_cand_max', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rem_min', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_cand_min', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('secteur_pourcent', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('formation_pourcent', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('loc_pourcent', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('age_moy', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('age_min', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('age_max', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('taux_reussite', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('commentaire', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('aff_intitule_post', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_nb_candidat', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_rem_moy', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_rem_max', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_age_cand_max', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_formation_cand_max', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_societe_prov_cand_max', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_rem_min', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_age_cand_min', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_formation_cand_min', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_societe_prov_cand_min', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_secteur_pourcent', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_formation_pourcent', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_loc_pourcent', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_age_moy', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_age_min', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_age_max', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('aff_commentaire', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('utilisateur_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('saved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}