<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CtrlLangue', 'doctrine');

/**
 * BaseCtrlLangue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $langue
 * @property Doctrine_Collection $LangueCandidat
 * 
 * @method string              getLangue()         Returns the current record's "langue" value
 * @method Doctrine_Collection getLangueCandidat() Returns the current record's "LangueCandidat" collection
 * @method CtrlLangue          setLangue()         Sets the current record's "langue" value
 * @method CtrlLangue          setLangueCandidat() Sets the current record's "LangueCandidat" collection
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCtrlLangue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ctrl_langue');
        $this->hasColumn('langue', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LangueCandidat', array(
             'local' => 'langue',
             'foreign' => 'langue'));
    }
}