<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LangueCandidat', 'doctrine');

/**
 * BaseLangueCandidat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $candidat_id
 * @property string $langue
 * @property Candidat $Candidat
 * @property CtrlLangue $CtrlLangue
 * 
 * @method integer        getCandidatId()  Returns the current record's "candidat_id" value
 * @method string         getLangue()      Returns the current record's "langue" value
 * @method Candidat       getCandidat()    Returns the current record's "Candidat" value
 * @method CtrlLangue     getCtrlLangue()  Returns the current record's "CtrlLangue" value
 * @method LangueCandidat setCandidatId()  Sets the current record's "candidat_id" value
 * @method LangueCandidat setLangue()      Sets the current record's "langue" value
 * @method LangueCandidat setCandidat()    Sets the current record's "Candidat" value
 * @method LangueCandidat setCtrlLangue()  Sets the current record's "CtrlLangue" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLangueCandidat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('langue_candidat');
        $this->hasColumn('candidat_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('langue', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Candidat', array(
             'local' => 'candidat_id',
             'foreign' => 'id'));

        $this->hasOne('CtrlLangue', array(
             'local' => 'langue',
             'foreign' => 'langue'));
    }
}