<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CritereLibreCandidat', 'doctrine');

/**
 * BaseCritereLibreCandidat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $candidat_id
 * @property integer $critere_libre_id
 * @property integer $valide
 * @property Candidat $Candidat
 * @property CritereLibre $CritereLibre
 * 
 * @method integer              getCandidatId()       Returns the current record's "candidat_id" value
 * @method integer              getCritereLibreId()   Returns the current record's "critere_libre_id" value
 * @method integer              getValide()           Returns the current record's "valide" value
 * @method Candidat             getCandidat()         Returns the current record's "Candidat" value
 * @method CritereLibre         getCritereLibre()     Returns the current record's "CritereLibre" value
 * @method CritereLibreCandidat setCandidatId()       Sets the current record's "candidat_id" value
 * @method CritereLibreCandidat setCritereLibreId()   Sets the current record's "critere_libre_id" value
 * @method CritereLibreCandidat setValide()           Sets the current record's "valide" value
 * @method CritereLibreCandidat setCandidat()         Sets the current record's "Candidat" value
 * @method CritereLibreCandidat setCritereLibre()     Sets the current record's "CritereLibre" value
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCritereLibreCandidat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('critere_libre_candidat');
        $this->hasColumn('candidat_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('critere_libre_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('valide', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Candidat', array(
             'local' => 'candidat_id',
             'foreign' => 'id'));

        $this->hasOne('CritereLibre', array(
             'local' => 'critere_libre_id',
             'foreign' => 'id'));
    }
}