generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Candidat
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          candidat
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: "Liste des candidats"
        display: [id, nom, prenom, source]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
