<?php

/**
 * PlaquetteSecteur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opsearch-app
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PlaquetteSecteur extends BasePlaquetteSecteur
{
    /*
	*
	*	initData()
	*	Préparation des données en vu de leur exploitation /!\ ne doit pas sauvegarder
	*
	*/
	public function initData() {
            $secteurs = explode(';', $this->getSecteur());

            //récupération des données de la base
            $nb_candidats = Doctrine::getTable('Parcour')->countBySecteurs($secteurs);
            $nb_societes = Doctrine::getTable('Parcour')->countSocieteBySecteurs($secteurs);
            $nb_missions = Doctrine::getTable('Mission')->countBySecteurs($secteurs);
            $postes = Doctrine::getTable('Mission')->getIntituleposteBySecteurs($secteurs);
            $clients = Doctrine::getTable('Mission')->getClientBySecteurs($secteurs);

            $rem_min = Doctrine::getTable('Mission')->getRemMinBySecteurs($secteurs);
            $rem_max = Doctrine::getTable('Mission')->getRemMaxBySecteurs($secteurs);
            $mediane_salariale = ($rem_min['0']['MIN'] + $rem_max['0']['MAX']) / 2;

            //initalisation de l'objet
            $this->setNbCandidat($nb_candidats);
            $this->setNbSociete($nb_societes);
            $this->setNbMission($nb_missions);
            $this->setPoste(implode(';', $postes));
            $this->setClient(implode(';', $clients));
            $this->setMedianeSalariale($mediane_salariale);

            //return $this;
        }
}
