generator:
  class: sfDoctrineGenerator
  param:
    model_class:           mission
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          mission
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: "Liste des missions"
        layout: stacked
        display: [id, client, intituleposte, secteur, fonction]
        params:  |
          <b>%%client%%</b> - %%secteur%%
          <br />%%intituleposte%% - <em>%%fonction%%<em>
      filter:  ~
      form:    ~
      edit:
        title: "Modifier la mission %%client%% - %%intituleposte%%"
      new:     ~
